### ISSUE TITLE
Changing web port in docker compose doesnt work :(

### ISSUE THREAD

**Issue by pastorpflores** [WattRex/Battery-Experiments-Manager#36]
I want to change the web exposed port to :80.

I changed the value in `Battery-Experiments-Manager/devops/docker-compose.yml`

``` 
wattrex_web_server:
    build:
      context: ../
      dockerfile: ./devops/web_server/Dockerfile.web_server
    image: javibu13/wattrex-web-server:latest
    container_name: wattrex_web_server
    restart: always
    ports:
      - "80:8000"
```

then shut down the server with './deploy.sh force-stop' and re-launch it with './deploy.sh' and it hasn't changed :(

Grasias de antemano 👍
